### ISSUE TITLE
我想自己做个火绒剑，另外集成一些电脑管家的能力，这个您有什么看法不

### ISSUE THREAD

**Issue by xx-zhang** [szdyg/HRSword#1]
- 火绒键，这个就用osquery之类的进行审计
- 查杀、补丁，运行监护 这个可能需要学习win api才可以把

我做过linux版本的 基于 auditd+netlink/selinux + Seccomp-filters （...）

但是关于windows我的了解很薄弱，不知道怎么来做。现在windows sdk更新快，要是兼容xp+也麻烦 （产品化的话） 。

**Comment by kihlh** [comment]
市面上的开源ark有很多，要实现，都是要会写驱动还有要有数字签名(微软认证)

**Comment by xx-zhang** [comment]
> 市面上的开源ark有很多，要实现，都是要会写驱动还有要有数字签名(微软认证)

@kihlh ark大多数都是静态的，我是想要动态的，后台执行的那种，装了后就是edr不需要看，自己根据我们的规则比如新增恶意程序、篡改等产生告警。

**Comment by kihlh** [comment]
> > 市面上的开源ark有很多，要实现，都是要会写驱动还有要有数字签名(微软认证)
> 
> @kihlh ark大多数都是静态的，我是想要动态的，后台执行的那种，装了后就是edr不需要看，自己根据我们的规则比如新增恶意程序、篡改等产生告警。

这个一般都是靠白加黑，hook系统dll实现的

**Comment by xx-zhang** [comment]
@kihlh 您说的是绕过检查么，我说的是系统行为审计。 要是防御肯定是你这种操作，就是只允许某些健康签名，可信hash的进程运行。  但是大多数工作者他们的电脑上都不会创建这些策略，我是要监护他们的电脑，比如父母的电脑
